
#Settings for Inventory HUD
[inventoryhud]
	#Inventory HUD mini mode
	invMini = false
	#Inventory HUD vertical mode
	invVert = false
	#Inventory HUD alpha
	#Range: 0 ~ 100
	invAlpha = 0
	#Toggle on by default
	byDefault = false
	#Animate recently picked up items
	animatedInv = true
	#Hide background if inventory is empty
	hideBackground = false
	#Show Inventory HUD when debug menu is open
	invWithDebug = true

#Settings for ArmorStatus HUD
[armorhud]
	#Is Armor Damage HUD enabled
	ArmorDamage = true
	#Hide if durability is above this (in percentage):
	#Range: 0 ~ 100
	armAbove = 100
	#Show/Hide armor
	showArmor = false
	#Show/Hide armor
	showMain = false
	#Show/Hide armor
	showOff = false
	#Show/Hide armor
	showArrows = false
	#Show/Hide armor
	showInv = false
	#Armor HUD durability view (PERCENTAGE, DAMAGE, DAMAGE LEFT)
	#Allowed Values: PERCENTAGE, DAMAGE, DAMAGE_LEFT, OFF
	armView = "OFF"
	#Show item durability bar
	armBars = true
	#Move all items at once or each one
	moveAll = false
	#Show/Hide empty slot icon
	showEmpty = true
	#Show overall count of items in main/off hand
	showCount = true
	#ArmorHUD scale in persentage from 50 to 150
	#Range: 50 ~ 150
	armScale = 100
	#Show Armor HUD when debug menu is open
	armWithDebug = true
	#Show arrows count when no weapon in your hands
	showArrowsWithoutWeapon = true

#Settings for Potions HUD
[potionshud]
	#Is Potions HUD enabled
	Potions = true
	#Potion HUD alpha
	#Range: 0 ~ 100
	potAlpha = 100
	#Potion HUD gap
	#Range: -5 ~ 5
	potGap = -1
	#Potion HUD mini mode
	potMini = true
	#Potion HUD horizontal mode
	potHor = false
	#Full bar duration
	#Range: > 1
	barDuration = 300
	#Show hidden effects
	showHiddenEffects = true
	#Disable icons for effects in this list
	effectsBlackList = []
	#Show Potion HUD when debug menu is open
	potWithDebug = true
	#Show all levels of effects
	potionLevels = true

#DONT TOUCH THESE FIELDS!
[positions]
	#Inventory HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invValign = "TOP"
	#Inventory HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHalign = "MIDDLE"
	#Inventory HUD position (X)
	#Range: -9999 ~ 9999
	xPos = 0
	#Inventory HUD position (Y)
	#Range: -9999 ~ 9999
	yPos = 1
	#Armor HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	armValign = "BOTTOM"
	#Armor HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	armHalign = "RIGHT"
	#Armor HUD position (X)
	#Range: -9999 ~ 9999
	xArmPos = 91
	#Armor HUD position (Y)
	#Range: -9999 ~ 9999
	yArmPos = 52
	#Potion HUD vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	potValign = "CENTER"
	#Potion HUD horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	potHalign = "RIGHT"
	#Potion HUD position (X)
	#Range: -9999 ~ 9999
	xPotionPos = 46
	#Potion HUD position (Y)
	#Range: -9999 ~ 9999
	yPotionPos = 34
	#Helmet position (X)
	#Range: -9999 ~ 9999
	helmPosX = 72
	#Helmet position (Y)
	#Range: -9999 ~ 9999
	helmPosY = 52
	#Chestplate position (X)
	#Range: -9999 ~ 9999
	chestPosX = 56
	#Chestplate position (Y)
	#Range: -9999 ~ 9999
	chestPosY = 52
	#Leggings position (X)
	#Range: -9999 ~ 9999
	legPosX = 40
	#Leggings position (Y)
	#Range: -9999 ~ 9999
	legPosY = 52
	#Boots position (X)
	#Range: -9999 ~ 9999
	bootPosX = 24
	#Boots position (Y)
	#Range: -9999 ~ 9999
	bootPosY = 52
	#MainHand position (X)
	#Range: -9999 ~ 9999
	mainPosX = 18
	#MainHand position (Y)
	#Range: -9999 ~ 9999
	mainPosY = 18
	#OffHand position (X)
	#Range: -9999 ~ 9999
	offPosX = 18
	#OffHand position (Y)
	#Range: -9999 ~ 9999
	offPosY = 34
	#Arrows position (X)
	#Range: -9999 ~ 9999
	arrPosX = 2
	#Arrows position (Y)
	#Range: -9999 ~ 9999
	arrPosY = 34
	#InvIcon position (X)
	#Range: -9999 ~ 9999
	invPosX = 2
	#InvIcon position (Y)
	#Range: -9999 ~ 9999
	invPosY = 18
	#Helmet horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	helmHal = "MIDDLE"
	#Helmet vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	helmVal = "TOP"
	#Chestplate horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	chestHal = "MIDDLE"
	#Chestplate vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	chestVal = "TOP"
	#Leggings horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	legHal = "MIDDLE"
	#Leggings vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	legVal = "TOP"
	#Boots horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	bootHal = "MIDDLE"
	#Boots vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	bootVal = "TOP"
	#MainHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	mainHal = "RIGHT"
	#MainHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	mainVal = "BOTTOM"
	#OffHand horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	offHal = "RIGHT"
	#OffHand vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	offVal = "BOTTOM"
	#Arrows horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	arrHal = "LEFT"
	#Arrows vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	arrVal = "BOTTOM"
	#InvIcon horizontal align
	#Allowed Values: LEFT, MIDDLE, RIGHT
	invHal = "LEFT"
	#InvIcon vertical align
	#Allowed Values: TOP, CENTER, BOTTOM
	invVal = "BOTTOM"

#Notification settings
[notification]
	#Last notified mod version
	lastNotifiedVersion = "0.5.1.f"
	#Notify more than once
	keepNotifying = true

